# Generated by Django 4.1.2 on 2022-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_company_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
