# Generated by Django 4.1.2 on 2022-10-29 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_company_year_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 2, 21, 42, 834244)),
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.FloatField(default=5.6),
        ),
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(),
        ),
    ]
