# Generated by Django 4.0.5 on 2022-10-29 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_company_email_remove_company_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 3, 3, 32, 170730)),
        ),
    ]
