# Generated by Django 4.1.2 on 2022-10-30 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_company_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 6, 47, 20, 780690)),
        ),
    ]
