# Generated by Django 4.0.5 on 2022-10-30 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 6, 27, 34, 882697)),
        ),
    ]
