# Generated by Django 4.0.5 on 2022-10-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_company_date'),
        ('student', '0006_company_date'),
    ]

    operations = [
    ]
