<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-10-30 04:12
=======
# Generated by Django 4.0.5 on 2022-10-30 04:34
>>>>>>> 60b972bae28bd65a701555290d95f1fa48ad484c

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 9, 42, 3, 30226)),
=======
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 10, 4, 27, 286760)),
>>>>>>> 60b972bae28bd65a701555290d95f1fa48ad484c
        ),
    ]
