<<<<<<< HEAD
=======
# Generated by Django 4.1.2 on 2022-10-30 06:32

>>>>>>> 6006e95e6f5f3987291c2026b49993fefd8b80d1
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 12, 2, 0, 885066)),
        ),
    ]