<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-10-30 06:31
=======
# Generated by Django 4.1.2 on 2022-10-30 06:32
>>>>>>> 532e2d2328f6caeecfc82ca9e25f4ea58742c510

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 12, 1, 2, 404256)),
=======
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 12, 2, 0, 885066)),
>>>>>>> 532e2d2328f6caeecfc82ca9e25f4ea58742c510
        ),
    ]
