# Generated by Django 4.0.5 on 2022-10-30 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_company_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='jobid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 12, 6, 45, 785534)),
        ),
    ]
