# Generated by Django 4.1.2 on 2022-10-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_company_date'),
        ('student', '0013_company_jobid_alter_company_date'),
    ]

    operations = [
    ]
